import { MigrationInterface, QueryRunner } from "typeorm";

export class Initial1765879028056 implements MigrationInterface {
    name = 'Initial1765879028056'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "user" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying, "name" character varying, "avatar_url" character varying, "password_hash" character varying, "provider" character varying NOT NULL DEFAULT 'email', "provider_id" character varying, "email_verified_at" TIMESTAMP, "is_active" boolean NOT NULL DEFAULT true, "role" character varying NOT NULL DEFAULT 'user', "first_name" character varying, "last_name" character varying, "social_id" character varying, "external_id" character varying, "casdoor_id" character varying, "permissions" jsonb, "last_login" TIMESTAMP, "failed_login_attempts" integer NOT NULL DEFAULT '0', "locked_until" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"), CONSTRAINT "UQ_d9479cbc9c65660b7cf9b657954" UNIQUE ("external_id"), CONSTRAINT "UQ_63b51505950c7d3dd877c448acb" UNIQUE ("casdoor_id"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e12875dfb3b1d92d7d7c5377e2" ON "user" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_5e3a2b86fd9a9c22c266ae0473" ON "user" ("provider_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7a4fd2a547828e5efe420e50d1" ON "user" ("first_name") `);
        await queryRunner.query(`CREATE INDEX "IDX_6937e802be2946855a3ad0e6be" ON "user" ("last_name") `);
        await queryRunner.query(`CREATE INDEX "IDX_0cd76a8cdee62eeff31d384b73" ON "user" ("social_id") `);
        await queryRunner.query(`CREATE TABLE "workspace" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "slug" character varying NOT NULL, "avatar_url" character varying, "plan" character varying NOT NULL DEFAULT 'free', "owner_id" uuid NOT NULL, "deleted_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_0d706c438a9b1ae0ac9806a201a" UNIQUE ("slug"), CONSTRAINT "PK_ca86b6f9b3be5fe26d307d09b49" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0d706c438a9b1ae0ac9806a201" ON "workspace" ("slug") `);
        await queryRunner.query(`CREATE TABLE "workspace_member" ("workspace_id" uuid NOT NULL, "user_id" uuid NOT NULL, "role" character varying NOT NULL DEFAULT 'member', "joined_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0eab76d5a9c509930a9f3d7a104" PRIMARY KEY ("workspace_id", "user_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0eab76d5a9c509930a9f3d7a10" ON "workspace_member" ("workspace_id", "user_id") `);
        await queryRunner.query(`CREATE TABLE "knowledge_base" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspace_id" uuid, "name" character varying NOT NULL, "description" character varying, "chunk_size" integer NOT NULL DEFAULT '1000', "chunk_overlap" integer NOT NULL DEFAULT '200', "embedding_model" character varying NOT NULL DEFAULT 'text-embedding-004', "ai_provider_id" uuid, "rag_model" character varying, "similarity_threshold" double precision NOT NULL DEFAULT '0.7', "top_k" integer NOT NULL DEFAULT '5', "live_version_id" uuid, "created_by" uuid NOT NULL, "icon" character varying, "color" character varying NOT NULL DEFAULT '#3B82F6', "is_public" boolean NOT NULL DEFAULT false, "total_documents" integer NOT NULL DEFAULT '0', "total_size" bigint NOT NULL DEFAULT '0', "tags" text, "deleted_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_19d3f52f6da1501b7e235f1da5c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f39683bc3c87e158ee5afffdba" ON "knowledge_base" ("workspace_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8ae166c823e535eb731f333522" ON "knowledge_base" ("ai_provider_id") `);
        await queryRunner.query(`CREATE TABLE "kb_folder" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "knowledge_base_id" uuid NOT NULL, "parent_id" uuid, "name" character varying NOT NULL, "path" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b9ecced097312ba705828ad18f6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d75bd458c36ccad6a3d784cfb8" ON "kb_folder" ("knowledge_base_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_161009326bd37f66e42195ef61" ON "kb_folder" ("parent_id") `);
        await queryRunner.query(`CREATE TABLE "kb_document" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "knowledge_base_id" uuid NOT NULL, "folder_id" uuid, "title" character varying NOT NULL, "slug" character varying, "type" character varying NOT NULL DEFAULT 'file', "source_url" character varying, "file_url" character varying, "file_type" character varying, "file_size" bigint, "current_version_id" uuid, "status" character varying NOT NULL DEFAULT 'pending', "tags" text, "metadata" jsonb, "created_by" uuid NOT NULL, "name" character varying, "content" text, "mime_type" character varying, "processing_status" character varying, "processing_error" text, "chunk_count" integer NOT NULL DEFAULT '0', "deleted_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_cfd7a475c9ae4d40a976c8bbb65" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6ee0459e7db0b730836e102d9b" ON "kb_document" ("knowledge_base_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e0a623b6a641e6cb084ffd1ae8" ON "kb_document" ("folder_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b29ab77551196c32dbf229c477" ON "kb_document" ("status") `);
        await queryRunner.query(`CREATE TABLE "kb_document_version" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "document_id" uuid NOT NULL, "version" integer NOT NULL, "version_label" character varying, "content_text" text, "content_html" text, "token_count" integer NOT NULL DEFAULT '0', "chunk_count" integer NOT NULL DEFAULT '0', "status" character varying NOT NULL DEFAULT 'pending', "is_live" boolean NOT NULL DEFAULT false, "qdrant_collection" character varying, "embedding_model" character varying, "processing_started_at" TIMESTAMP, "processing_completed_at" TIMESTAMP, "error_message" text, "created_by" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_33b9d0a0699eacfbd6c40df6bb7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c348ba14b55e6e3452b050a612" ON "kb_document_version" ("document_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_fe4cabddacd8bea491dda43610" ON "kb_document_version" ("document_id", "version") `);
        await queryRunner.query(`CREATE TABLE "rag_feedback" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "message_id" uuid NOT NULL, "rating" integer NOT NULL, "comment" text, "created_by" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ac681653e6fd694d603a4674999" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ba6efe5217f9ccca718f480f96" ON "rag_feedback" ("message_id") `);
        await queryRunner.query(`CREATE TABLE "kb_chunk" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "document_id" uuid NOT NULL, "knowledge_base_id" uuid NOT NULL, "content" text NOT NULL, "chunk_index" integer NOT NULL, "start_char" integer NOT NULL, "end_char" integer NOT NULL, "token_count" integer, "metadata" jsonb, "vector_id" character varying, "embedding_status" character varying NOT NULL DEFAULT 'pending', "embedding_error" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "documentId" uuid, CONSTRAINT "PK_53f290237ff06a63b55ae7f23c9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f37a6fd48b5ba27e7da2d4a8e6" ON "kb_chunk" ("document_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e9e43161d0e1e48cc608513802" ON "kb_chunk" ("knowledge_base_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4f4af60aee1133f7e8a8043cfb" ON "kb_chunk" ("vector_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2b11e5e325ab1cf316a7b1d2b2" ON "kb_chunk" ("embedding_status") `);
        await queryRunner.query(`CREATE TABLE "ai_providers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying NOT NULL, "label" character varying NOT NULL, "icon" character varying, "description" text, "required_fields" jsonb NOT NULL DEFAULT '[]', "optional_fields" jsonb NOT NULL DEFAULT '[]', "default_values" jsonb NOT NULL DEFAULT '{}', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ebb21740e10748770b54434db59" UNIQUE ("key"), CONSTRAINT "PK_de28ebefc0fb425c37b27a4c0a7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ai_provider_configs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "provider_id" uuid NOT NULL, "model" character varying NOT NULL, "api_key" character varying NOT NULL, "base_url" character varying, "api_version" character varying, "timeout" integer, "use_stream" boolean NOT NULL DEFAULT true, "owner_type" character varying NOT NULL, "owner_id" uuid, "is_default" boolean NOT NULL DEFAULT false, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5c72661bb93d1e6263172f452db" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7299ed156a084d7e97df80b7ff" ON "ai_provider_configs" ("provider_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2bdd8f45e064bac6f99cbbe91d" ON "ai_provider_configs" ("owner_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_b4e4ef106d84e38e8577cd965d" ON "ai_provider_configs" ("owner_id") `);
        await queryRunner.query(`CREATE TABLE "user_ai_provider_configs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "provider_id" uuid NOT NULL, "display_name" character varying NOT NULL, "config" jsonb NOT NULL, "model_list" jsonb NOT NULL DEFAULT '[]', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b5931888df2b024311f8a132373" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bca82934cd53e143c74a2ff97c" ON "user_ai_provider_configs" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ec0f1703bed5fb29ea5e0afe16" ON "user_ai_provider_configs" ("provider_id") `);
        await queryRunner.query(`CREATE TABLE "workspace_ai_provider_configs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspace_id" uuid NOT NULL, "provider_id" uuid NOT NULL, "display_name" character varying NOT NULL, "config" jsonb NOT NULL, "model_list" jsonb NOT NULL DEFAULT '[]', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_453a175908363f730ee3ad12c4c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3522a3e473b56a703fe8d98c95" ON "workspace_ai_provider_configs" ("workspace_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2a55b8ba19368d0e6499ba5df1" ON "workspace_ai_provider_configs" ("provider_id") `);
        await queryRunner.query(`CREATE TABLE "ai_usage_log" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspace_id" uuid NOT NULL, "user_id" uuid NOT NULL, "provider" character varying NOT NULL, "model" character varying NOT NULL, "input_tokens" integer NOT NULL, "output_tokens" integer NOT NULL, "cost" numeric(10,6) NOT NULL DEFAULT '0', "requested_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b51c8fcf98a77ad8bef55c91bd5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d4b3d0a0eac463e2224513fff7" ON "ai_usage_log" ("workspace_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d7b00762ea27339b5f6ea53bfa" ON "ai_usage_log" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_18f3bc73d7d2692f732cc974f0" ON "ai_usage_log" ("requested_at") `);
        await queryRunner.query(`CREATE TABLE "system_ai_settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "default_provider_id" character varying, "default_model" character varying, "min_temperature" numeric(3,1) NOT NULL DEFAULT '0', "max_temperature" numeric(3,1) NOT NULL DEFAULT '2', "content_moderation" boolean NOT NULL DEFAULT true, "safe_fallbacks" boolean NOT NULL DEFAULT true, "context_aware" boolean NOT NULL DEFAULT true, "max_requests_per_hour" integer NOT NULL DEFAULT '1000', "max_requests_per_user" integer NOT NULL DEFAULT '100', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4ea8c546ef61546cb93977c6d9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "webhook_event" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "channel_id" uuid NOT NULL, "raw_payload" jsonb NOT NULL, "status" character varying NOT NULL DEFAULT 'pending', "error_message" text, "processed_at" TIMESTAMP, "received_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0f56d2f40f5ec823acf8e8edad1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0253cc148d22e4ba68ca3ededf" ON "webhook_event" ("channel_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_63a1ffd56c6903021d2c5b6aaa" ON "webhook_event" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_c9c20a97f6b381386a315f74c3" ON "webhook_event" ("received_at") `);
        await queryRunner.query(`CREATE TABLE "plan" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "price_monthly" numeric(10,2) NOT NULL, "price_yearly" numeric(10,2) NOT NULL, "max_bots" integer NOT NULL, "max_messages" integer NOT NULL, "max_storage_gb" integer NOT NULL, "features" jsonb, CONSTRAINT "UQ_8aa73af67fa634d33de9bf874ab" UNIQUE ("name"), CONSTRAINT "PK_54a2b686aed3b637654bf7ddbb3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "subscription" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspace_id" uuid NOT NULL, "plan_id" uuid NOT NULL, "status" character varying NOT NULL DEFAULT 'active', "current_period_end" TIMESTAMP NOT NULL, "stripe_customer_id" character varying, "stripe_subscription_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8c3e00ebd02103caa1174cd5d9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6026acc5aa817269a5f7463526" ON "subscription" ("workspace_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_5fde988e5d9b9a522d70ebec27" ON "subscription" ("plan_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c60cbdbd21c49a01596ec24d1f" ON "subscription" ("stripe_customer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4919f4488c35799176dfd3c143" ON "subscription" ("stripe_subscription_id") `);
        await queryRunner.query(`CREATE TABLE "usage_quota" ("workspace_id" uuid NOT NULL, "period_start" date NOT NULL, "messages_used" integer NOT NULL DEFAULT '0', "storage_used_gb" numeric(10,2) NOT NULL DEFAULT '0', "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_192fa04382405c62d6e7a0eedf0" PRIMARY KEY ("workspace_id", "period_start"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_192fa04382405c62d6e7a0eedf" ON "usage_quota" ("workspace_id", "period_start") `);
        await queryRunner.query(`CREATE TABLE "invoice" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspace_id" uuid NOT NULL, "subscription_id" uuid NOT NULL, "amount" numeric(10,2) NOT NULL, "status" character varying NOT NULL DEFAULT 'draft', "pdf_url" character varying, "period_start" date NOT NULL, "period_end" date NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_15d25c200d9bcd8a33f698daf18" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a85d07a63679df4dd094bfc756" ON "invoice" ("workspace_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_5d9508325a862b5b3c7c819de3" ON "invoice" ("subscription_id") `);
        await queryRunner.query(`CREATE TABLE "status" ("id" integer NOT NULL, "name" character varying NOT NULL, CONSTRAINT "PK_e12743a7086ec826733f54e1d95" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "session" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "hash" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "userId" uuid, CONSTRAINT "PK_f55da76ac1c3ac420f444d2ff11" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3d2f174ef04fb312fdebd0ddc5" ON "session" ("userId") `);
        await queryRunner.query(`CREATE TABLE "permission" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, "resource" character varying NOT NULL, "action" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_240853a0c3353c25fb12434ad33" UNIQUE ("name"), CONSTRAINT "PK_3b8b97af9d9d8807e41e6f48362" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "role" ("id" integer NOT NULL, "name" character varying NOT NULL, "description" character varying, "casdoor_role_name" character varying, CONSTRAINT "PK_b36bcfe02fc8de3c57a8b2391c2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notification" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "workspace_id" uuid NOT NULL, "title" character varying NOT NULL, "message" text NOT NULL, "type" character varying NOT NULL DEFAULT 'info', "is_read" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_705b6c7cdf9b2c2ff7ac7872cb7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_928b7aa1754e08e1ed7052cb9d" ON "notification" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9f7d684c30d9d0cdbc24322de8" ON "notification" ("workspace_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_aedc307c7e60ecb138e3f90ff8" ON "notification" ("is_read") `);
        await queryRunner.query(`CREATE INDEX "IDX_8bdc07e9c41ce8d83730f0f5d8" ON "notification" ("created_at") `);
        await queryRunner.query(`CREATE TABLE "node_type" ("id" character varying(100) NOT NULL, "label" character varying NOT NULL, "category" character varying NOT NULL, "icon" character varying NOT NULL, "color" character varying NOT NULL, "description" text, "isActive" boolean NOT NULL DEFAULT true, "properties" jsonb NOT NULL DEFAULT '[]', "sortOrder" integer NOT NULL DEFAULT '0', "outputSchema" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_21db5612f4dbffd0e468819c4ae" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "channel_credential" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "provider" character varying NOT NULL, "workspaceId" uuid, "name" character varying, "clientId" character varying, "clientSecret" character varying, "scopes" character varying, "isActive" boolean NOT NULL DEFAULT true, "metadata" jsonb DEFAULT '{}', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_dac10e98607782ecfb6bd9b141e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7759e3294e12c1bd976f2ca8ac" ON "channel_credential" ("provider") `);
        await queryRunner.query(`CREATE INDEX "IDX_45dbb885e2a77019931fc5ed8f" ON "channel_credential" ("workspaceId") `);
        await queryRunner.query(`CREATE TABLE "channel_connection" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "type" character varying NOT NULL, "credentialId" uuid, "workspaceId" uuid, "bot_id" uuid, "accessToken" character varying, "refreshToken" character varying, "expiresAt" TIMESTAMP, "metadata" jsonb DEFAULT '{}', "status" character varying NOT NULL DEFAULT 'active', "connectedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f0b0b90fa3837ad5470c942462d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_81d0c0117227d233206d06fa95" ON "channel_connection" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_49ac0d03296afd3cad2a4be75b" ON "channel_connection" ("credentialId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5ac913b616a1320e4e443f9ee6" ON "channel_connection" ("workspaceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a5a2e06b4f4afbdaee17a9df17" ON "channel_connection" ("bot_id") `);
        await queryRunner.query(`CREATE TABLE "flow" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, "status" character varying NOT NULL DEFAULT 'draft', "version" integer NOT NULL DEFAULT '1', "nodes" jsonb NOT NULL DEFAULT '{"nodes":[],"edges":[]}', "edges" jsonb NOT NULL DEFAULT '[]', "ownerId" uuid, "teamId" uuid, "visibility" character varying NOT NULL DEFAULT 'private', "tags" text, "category" character varying, "icon" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6c2ad4a3e86394cd9bb7a80a228" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "flow_version" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "bot_id" uuid, "version" integer NOT NULL, "name" character varying, "description" text, "status" character varying NOT NULL DEFAULT 'draft', "published_at" TIMESTAMP, "created_by" uuid, "flow" jsonb NOT NULL, "is_published" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "flowId" uuid NOT NULL, "data" jsonb NOT NULL, "versionNumber" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2f20a52dcddf98d3fafe621a9f5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "node_execution" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "executionId" uuid NOT NULL, "nodeId" character varying NOT NULL, "nodeName" character varying NOT NULL, "type" character varying NOT NULL, "input" jsonb, "output" jsonb, "error" character varying, "startTime" bigint NOT NULL, "endTime" bigint, "status" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a78a4d229919cfb123d090e71e5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_38fca24c8eadabf06167f4d6c9" ON "node_execution" ("executionId") `);
        await queryRunner.query(`CREATE TABLE "flow_execution" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "executionId" character varying NOT NULL, "flowId" uuid NOT NULL, "status" character varying NOT NULL, "startTime" bigint NOT NULL, "endTime" bigint, "result" jsonb, "error" character varying, "workspaceId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_b12e2bba2745c94014eed8a0209" UNIQUE ("executionId"), CONSTRAINT "PK_9298d4abb879af4bca7621dab76" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b12e2bba2745c94014eed8a020" ON "flow_execution" ("executionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_82bbbc66b3d756c9b6195e54a2" ON "flow_execution" ("flowId") `);
        await queryRunner.query(`CREATE TABLE "file" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "path" character varying NOT NULL, "bucket" character varying NOT NULL DEFAULT 'images', CONSTRAINT "PK_36b46d232307066b3a2c9ea3a1d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ai_conversation" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "title" character varying NOT NULL, "bot_id" uuid, "use_knowledge_base" boolean NOT NULL DEFAULT false, "metadata" jsonb NOT NULL DEFAULT '{}', "messages" jsonb NOT NULL DEFAULT '[]', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, CONSTRAINT "PK_c5c36eee51de52a151fb73f7a51" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1bdb0ba34522870a1d86dc4514" ON "ai_conversation" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8718c0c649f54b2e26e819018e" ON "ai_conversation" ("bot_id") `);
        await queryRunner.query(`CREATE TABLE "bot" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspace_id" uuid NOT NULL, "name" character varying NOT NULL, "description" character varying, "avatar_url" character varying, "default_language" character varying NOT NULL DEFAULT 'en', "timezone" character varying NOT NULL DEFAULT 'UTC', "status" character varying NOT NULL DEFAULT 'draft', "created_by" uuid NOT NULL, "icon" character varying DEFAULT 'FiMessageSquare', "is_active" boolean NOT NULL DEFAULT true, "flow_id" uuid, "system_prompt" text, "functions" text, "function_config" jsonb, "ai_provider_id" uuid, "ai_model_name" character varying, "ai_parameters" jsonb, "knowledge_base_ids" text, "enable_auto_learn" boolean NOT NULL DEFAULT false, "allowed_origins" jsonb, "welcome_message" character varying, "placeholder_text" character varying, "primary_color" character varying, "widget_position" character varying NOT NULL DEFAULT 'bottom-right', "widget_button_size" character varying NOT NULL DEFAULT 'medium', "show_avatar" boolean NOT NULL DEFAULT true, "show_timestamp" boolean NOT NULL DEFAULT true, "widget_enabled" boolean NOT NULL DEFAULT true, "widget_config" jsonb, "deleted_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bc6d59d7870eb2efd5f7f61e5ca" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e45750f69e8b0280974c298b82" ON "bot" ("workspace_id") `);
        await queryRunner.query(`CREATE TABLE "bot_knowledge_base" ("bot_id" uuid NOT NULL, "knowledge_base_id" uuid NOT NULL, "priority" integer NOT NULL DEFAULT '1', "rag_settings" jsonb, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_159a73113affedc7d5638ce6c2b" PRIMARY KEY ("bot_id", "knowledge_base_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_159a73113affedc7d5638ce6c2" ON "bot_knowledge_base" ("bot_id", "knowledge_base_id") `);
        await queryRunner.query(`CREATE TABLE "channel" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "bot_id" uuid NOT NULL, "type" character varying NOT NULL, "name" character varying NOT NULL, "config" jsonb, "is_active" boolean NOT NULL DEFAULT true, "connected_at" TIMESTAMP, "created_by" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_590f33ee6ee7d76437acf362e39" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_82da258fe45382a03c820a8daf" ON "channel" ("bot_id") `);
        await queryRunner.query(`CREATE TABLE "conversation" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "bot_id" uuid NOT NULL, "channel_type" character varying NOT NULL DEFAULT 'web', "channel_id" uuid, "contact_name" character varying, "contact_avatar" character varying, "metadata" jsonb NOT NULL DEFAULT '{}', "status" character varying NOT NULL DEFAULT 'active', "last_message_at" TIMESTAMP, "handover_ticket_id" uuid, "external_id" character varying, "deleted_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_864528ec4274360a40f66c29845" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_aaebf689e2996177947248df93" ON "conversation" ("bot_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_91fdb6236859404ddf7c5f6437" ON "conversation" ("channel_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0d448862b6090e5239102fb2db" ON "conversation" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_4414991bced54350c7ad1378fc" ON "conversation" ("last_message_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_b6a81d0030252361a6a7326dd5" ON "conversation" ("external_id") `);
        await queryRunner.query(`CREATE TABLE "message" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "conversation_id" uuid NOT NULL, "role" character varying NOT NULL DEFAULT 'user', "content" text NOT NULL, "attachments" jsonb, "metadata" jsonb NOT NULL DEFAULT '{}', "sources" jsonb, "tool_calls" jsonb, "feedback" character varying, "feedback_comment" text, "sender" character varying, "sent_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ba01f0a3e0123651915008bc578" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7fe3e887d78498d9c9813375ce" ON "message" ("conversation_id") `);
        await queryRunner.query(`CREATE TABLE "message_feedback" ("message_id" uuid NOT NULL, "rating" integer NOT NULL, "comment" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ca21e42f59ad7a1f2638a86aedf" PRIMARY KEY ("message_id"))`);
        await queryRunner.query(`CREATE TABLE "widget_version" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "bot_id" uuid NOT NULL, "version" character varying(20) NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'draft', "is_active" boolean NOT NULL DEFAULT false, "config" jsonb NOT NULL, "published_at" TIMESTAMP, "published_by" uuid, "cdn_url" character varying(500), "changelog" text, "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fd4fd7ecfa5a3c040d85ce9be7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_73d825a2b5257fecae3fa44391" ON "widget_version" ("bot_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_eec8048c9de6987375d69bce8f" ON "widget_version" ("bot_id", "is_active") WHERE is_active = true`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_869c687d5115dda182f23c3d7d" ON "widget_version" ("bot_id", "version") `);
        await queryRunner.query(`CREATE TABLE "widget_deployment" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "bot_id" uuid NOT NULL, "widget_version_id" uuid NOT NULL, "deployed_by" uuid, "deployed_at" TIMESTAMP NOT NULL DEFAULT NOW(), "deployment_type" character varying(20) NOT NULL, "previous_version_id" uuid, "rollback_reason" text, "traffic_percentage" integer NOT NULL DEFAULT '100', "status" character varying(20) NOT NULL, "metadata" jsonb, CONSTRAINT "PK_641e3fb1795f929ccdc94741648" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_46f3d06fc514b5dbd701949d22" ON "widget_deployment" ("bot_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_844910ae4694cdde8c1c428cc9" ON "widget_deployment" ("widget_version_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0cc3da9bd6517136ef4a68fec3" ON "widget_deployment" ("deployed_at") `);
        await queryRunner.query(`CREATE TABLE "audit_log" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "workspace_id" uuid NOT NULL, "action" character varying NOT NULL, "resource_type" character varying NOT NULL, "resource_id" character varying NOT NULL, "details" jsonb, "ip_address" character varying, "user_agent" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_07fefa57f7f5ab8fc3f52b3ed0b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cb11bd5b662431ea0ac455a27d" ON "audit_log" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d65f841d6520dc60a9dfcb9367" ON "audit_log" ("workspace_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_951e6339a77994dfbad976b35c" ON "audit_log" ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_4a7f36346480a56b810efea4a2" ON "audit_log" ("resource_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_2ad7930a7c2af80585c8c1b770" ON "audit_log" ("created_at") `);
        await queryRunner.query(`CREATE TABLE "data_access_log" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "workspace_id" uuid NOT NULL, "table_name" character varying NOT NULL, "record_id" character varying NOT NULL, "action" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_08f41b4079fc059dfbba953808b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_540a1d7e19f73eed9317c514b7" ON "data_access_log" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f7f36a37f00bf828c64235a64f" ON "data_access_log" ("workspace_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1306d6c971218f52de9eb25871" ON "data_access_log" ("table_name") `);
        await queryRunner.query(`CREATE INDEX "IDX_7b6ddcbc20f35c452fbde742e8" ON "data_access_log" ("created_at") `);
        await queryRunner.query(`CREATE TABLE "role_permission" ("role_id" integer NOT NULL, "permission_id" uuid NOT NULL, CONSTRAINT "PK_19a94c31d4960ded0dcd0397759" PRIMARY KEY ("role_id", "permission_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3d0a7155eafd75ddba5a701336" ON "role_permission" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e3a3ba47b7ca00fd23be4ebd6c" ON "role_permission" ("permission_id") `);
        await queryRunner.query(`ALTER TABLE "flow_version" DROP COLUMN "flowId"`);
        await queryRunner.query(`ALTER TABLE "flow_version" DROP COLUMN "data"`);
        await queryRunner.query(`ALTER TABLE "flow_version" DROP COLUMN "versionNumber"`);
        await queryRunner.query(`ALTER TABLE "flow_version" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "flow_version" ADD "flowId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "flow_version" ADD "data" jsonb NOT NULL`);
        await queryRunner.query(`ALTER TABLE "flow_version" ADD "versionNumber" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "flow_version" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "flow_version" ALTER COLUMN "bot_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "flow_version" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "flow_version" ADD "description" character varying`);
        await queryRunner.query(`ALTER TABLE "flow_version" ALTER COLUMN "created_by" SET NOT NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_8c9b43712e39780ad1d53380b7" ON "flow_version" ("bot_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6fd20035420a32ac56139d17f6" ON "flow_version" ("bot_id", "version") `);
        await queryRunner.query(`ALTER TABLE "workspace" ADD CONSTRAINT "FK_988cf8ee530a5f8a2d56269955b" FOREIGN KEY ("owner_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workspace_member" ADD CONSTRAINT "FK_73d466cb93234025fe379fa5873" FOREIGN KEY ("workspace_id") REFERENCES "workspace"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workspace_member" ADD CONSTRAINT "FK_82b74268d8b7e1574fd744b3903" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "knowledge_base" ADD CONSTRAINT "FK_a47b1575e8f2c2cc377a9cc40f0" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "knowledge_base" ADD CONSTRAINT "FK_f39683bc3c87e158ee5afffdbac" FOREIGN KEY ("workspace_id") REFERENCES "workspace"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kb_folder" ADD CONSTRAINT "FK_d75bd458c36ccad6a3d784cfb81" FOREIGN KEY ("knowledge_base_id") REFERENCES "knowledge_base"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kb_folder" ADD CONSTRAINT "FK_161009326bd37f66e42195ef61d" FOREIGN KEY ("parent_id") REFERENCES "kb_folder"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kb_document" ADD CONSTRAINT "FK_6ee0459e7db0b730836e102d9b1" FOREIGN KEY ("knowledge_base_id") REFERENCES "knowledge_base"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kb_document" ADD CONSTRAINT "FK_e0a623b6a641e6cb084ffd1ae8c" FOREIGN KEY ("folder_id") REFERENCES "kb_folder"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kb_document" ADD CONSTRAINT "FK_e98a2d3732711bfa802d8de314e" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kb_document_version" ADD CONSTRAINT "FK_c348ba14b55e6e3452b050a6129" FOREIGN KEY ("document_id") REFERENCES "kb_document"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kb_document_version" ADD CONSTRAINT "FK_e828d02073fa95cca8fda16ad60" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rag_feedback" ADD CONSTRAINT "FK_8b0eac5cbe2159dc9070a1e52be" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kb_chunk" ADD CONSTRAINT "FK_9f2ef0102da59042a85e6f21fb0" FOREIGN KEY ("documentId") REFERENCES "kb_document"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_provider_configs" ADD CONSTRAINT "FK_7299ed156a084d7e97df80b7ff6" FOREIGN KEY ("provider_id") REFERENCES "ai_providers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_ai_provider_configs" ADD CONSTRAINT "FK_bca82934cd53e143c74a2ff97c5" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_ai_provider_configs" ADD CONSTRAINT "FK_ec0f1703bed5fb29ea5e0afe160" FOREIGN KEY ("provider_id") REFERENCES "ai_providers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workspace_ai_provider_configs" ADD CONSTRAINT "FK_3522a3e473b56a703fe8d98c950" FOREIGN KEY ("workspace_id") REFERENCES "workspace"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workspace_ai_provider_configs" ADD CONSTRAINT "FK_2a55b8ba19368d0e6499ba5df1b" FOREIGN KEY ("provider_id") REFERENCES "ai_providers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_usage_log" ADD CONSTRAINT "FK_d4b3d0a0eac463e2224513fff7c" FOREIGN KEY ("workspace_id") REFERENCES "workspace"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_usage_log" ADD CONSTRAINT "FK_d7b00762ea27339b5f6ea53bfac" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscription" ADD CONSTRAINT "FK_6026acc5aa817269a5f74635264" FOREIGN KEY ("workspace_id") REFERENCES "workspace"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscription" ADD CONSTRAINT "FK_5fde988e5d9b9a522d70ebec27c" FOREIGN KEY ("plan_id") REFERENCES "plan"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usage_quota" ADD CONSTRAINT "FK_3e28b611f0efceaff91771f9b04" FOREIGN KEY ("workspace_id") REFERENCES "workspace"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice" ADD CONSTRAINT "FK_a85d07a63679df4dd094bfc756a" FOREIGN KEY ("workspace_id") REFERENCES "workspace"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice" ADD CONSTRAINT "FK_5d9508325a862b5b3c7c819de3e" FOREIGN KEY ("subscription_id") REFERENCES "subscription"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "session" ADD CONSTRAINT "FK_3d2f174ef04fb312fdebd0ddc53" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "channel_connection" ADD CONSTRAINT "FK_49ac0d03296afd3cad2a4be75b2" FOREIGN KEY ("credentialId") REFERENCES "channel_credential"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "flow" ADD CONSTRAINT "FK_45e9c69589ca6ae78b28f255700" FOREIGN KEY ("ownerId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "node_execution" ADD CONSTRAINT "FK_38fca24c8eadabf06167f4d6c94" FOREIGN KEY ("executionId") REFERENCES "flow_execution"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_conversation" ADD CONSTRAINT "FK_4eb1cdcb75977fe6774fad6f654" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bot" ADD CONSTRAINT "FK_e45750f69e8b0280974c298b82f" FOREIGN KEY ("workspace_id") REFERENCES "workspace"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "flow_version" ADD CONSTRAINT "FK_8c9b43712e39780ad1d53380b74" FOREIGN KEY ("bot_id") REFERENCES "bot"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bot_knowledge_base" ADD CONSTRAINT "FK_d00741d566a15f9b57e535c022c" FOREIGN KEY ("bot_id") REFERENCES "bot"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "channel" ADD CONSTRAINT "FK_82da258fe45382a03c820a8daf4" FOREIGN KEY ("bot_id") REFERENCES "bot"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "channel" ADD CONSTRAINT "FK_bf9c25c4068a5913cf57cb3276e" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversation" ADD CONSTRAINT "FK_aaebf689e2996177947248df934" FOREIGN KEY ("bot_id") REFERENCES "bot"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message" ADD CONSTRAINT "FK_7fe3e887d78498d9c9813375ce2" FOREIGN KEY ("conversation_id") REFERENCES "conversation"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_feedback" ADD CONSTRAINT "FK_ca21e42f59ad7a1f2638a86aedf" FOREIGN KEY ("message_id") REFERENCES "message"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "widget_version" ADD CONSTRAINT "FK_73d825a2b5257fecae3fa443911" FOREIGN KEY ("bot_id") REFERENCES "bot"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "widget_deployment" ADD CONSTRAINT "FK_46f3d06fc514b5dbd701949d225" FOREIGN KEY ("bot_id") REFERENCES "bot"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "widget_deployment" ADD CONSTRAINT "FK_844910ae4694cdde8c1c428cc95" FOREIGN KEY ("widget_version_id") REFERENCES "widget_version"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "widget_deployment" ADD CONSTRAINT "FK_f987c08d3958a63f35012a2186d" FOREIGN KEY ("previous_version_id") REFERENCES "widget_version"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permission" ADD CONSTRAINT "FK_3d0a7155eafd75ddba5a7013368" FOREIGN KEY ("role_id") REFERENCES "role"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permission" ADD CONSTRAINT "FK_e3a3ba47b7ca00fd23be4ebd6cf" FOREIGN KEY ("permission_id") REFERENCES "permission"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "role_permission" DROP CONSTRAINT "FK_e3a3ba47b7ca00fd23be4ebd6cf"`);
        await queryRunner.query(`ALTER TABLE "role_permission" DROP CONSTRAINT "FK_3d0a7155eafd75ddba5a7013368"`);
        await queryRunner.query(`ALTER TABLE "widget_deployment" DROP CONSTRAINT "FK_f987c08d3958a63f35012a2186d"`);
        await queryRunner.query(`ALTER TABLE "widget_deployment" DROP CONSTRAINT "FK_844910ae4694cdde8c1c428cc95"`);
        await queryRunner.query(`ALTER TABLE "widget_deployment" DROP CONSTRAINT "FK_46f3d06fc514b5dbd701949d225"`);
        await queryRunner.query(`ALTER TABLE "widget_version" DROP CONSTRAINT "FK_73d825a2b5257fecae3fa443911"`);
        await queryRunner.query(`ALTER TABLE "message_feedback" DROP CONSTRAINT "FK_ca21e42f59ad7a1f2638a86aedf"`);
        await queryRunner.query(`ALTER TABLE "message" DROP CONSTRAINT "FK_7fe3e887d78498d9c9813375ce2"`);
        await queryRunner.query(`ALTER TABLE "conversation" DROP CONSTRAINT "FK_aaebf689e2996177947248df934"`);
        await queryRunner.query(`ALTER TABLE "channel" DROP CONSTRAINT "FK_bf9c25c4068a5913cf57cb3276e"`);
        await queryRunner.query(`ALTER TABLE "channel" DROP CONSTRAINT "FK_82da258fe45382a03c820a8daf4"`);
        await queryRunner.query(`ALTER TABLE "bot_knowledge_base" DROP CONSTRAINT "FK_d00741d566a15f9b57e535c022c"`);
        await queryRunner.query(`ALTER TABLE "flow_version" DROP CONSTRAINT "FK_8c9b43712e39780ad1d53380b74"`);
        await queryRunner.query(`ALTER TABLE "bot" DROP CONSTRAINT "FK_e45750f69e8b0280974c298b82f"`);
        await queryRunner.query(`ALTER TABLE "ai_conversation" DROP CONSTRAINT "FK_4eb1cdcb75977fe6774fad6f654"`);
        await queryRunner.query(`ALTER TABLE "node_execution" DROP CONSTRAINT "FK_38fca24c8eadabf06167f4d6c94"`);
        await queryRunner.query(`ALTER TABLE "flow" DROP CONSTRAINT "FK_45e9c69589ca6ae78b28f255700"`);
        await queryRunner.query(`ALTER TABLE "channel_connection" DROP CONSTRAINT "FK_49ac0d03296afd3cad2a4be75b2"`);
        await queryRunner.query(`ALTER TABLE "session" DROP CONSTRAINT "FK_3d2f174ef04fb312fdebd0ddc53"`);
        await queryRunner.query(`ALTER TABLE "invoice" DROP CONSTRAINT "FK_5d9508325a862b5b3c7c819de3e"`);
        await queryRunner.query(`ALTER TABLE "invoice" DROP CONSTRAINT "FK_a85d07a63679df4dd094bfc756a"`);
        await queryRunner.query(`ALTER TABLE "usage_quota" DROP CONSTRAINT "FK_3e28b611f0efceaff91771f9b04"`);
        await queryRunner.query(`ALTER TABLE "subscription" DROP CONSTRAINT "FK_5fde988e5d9b9a522d70ebec27c"`);
        await queryRunner.query(`ALTER TABLE "subscription" DROP CONSTRAINT "FK_6026acc5aa817269a5f74635264"`);
        await queryRunner.query(`ALTER TABLE "ai_usage_log" DROP CONSTRAINT "FK_d7b00762ea27339b5f6ea53bfac"`);
        await queryRunner.query(`ALTER TABLE "ai_usage_log" DROP CONSTRAINT "FK_d4b3d0a0eac463e2224513fff7c"`);
        await queryRunner.query(`ALTER TABLE "workspace_ai_provider_configs" DROP CONSTRAINT "FK_2a55b8ba19368d0e6499ba5df1b"`);
        await queryRunner.query(`ALTER TABLE "workspace_ai_provider_configs" DROP CONSTRAINT "FK_3522a3e473b56a703fe8d98c950"`);
        await queryRunner.query(`ALTER TABLE "user_ai_provider_configs" DROP CONSTRAINT "FK_ec0f1703bed5fb29ea5e0afe160"`);
        await queryRunner.query(`ALTER TABLE "user_ai_provider_configs" DROP CONSTRAINT "FK_bca82934cd53e143c74a2ff97c5"`);
        await queryRunner.query(`ALTER TABLE "ai_provider_configs" DROP CONSTRAINT "FK_7299ed156a084d7e97df80b7ff6"`);
        await queryRunner.query(`ALTER TABLE "kb_chunk" DROP CONSTRAINT "FK_9f2ef0102da59042a85e6f21fb0"`);
        await queryRunner.query(`ALTER TABLE "rag_feedback" DROP CONSTRAINT "FK_8b0eac5cbe2159dc9070a1e52be"`);
        await queryRunner.query(`ALTER TABLE "kb_document_version" DROP CONSTRAINT "FK_e828d02073fa95cca8fda16ad60"`);
        await queryRunner.query(`ALTER TABLE "kb_document_version" DROP CONSTRAINT "FK_c348ba14b55e6e3452b050a6129"`);
        await queryRunner.query(`ALTER TABLE "kb_document" DROP CONSTRAINT "FK_e98a2d3732711bfa802d8de314e"`);
        await queryRunner.query(`ALTER TABLE "kb_document" DROP CONSTRAINT "FK_e0a623b6a641e6cb084ffd1ae8c"`);
        await queryRunner.query(`ALTER TABLE "kb_document" DROP CONSTRAINT "FK_6ee0459e7db0b730836e102d9b1"`);
        await queryRunner.query(`ALTER TABLE "kb_folder" DROP CONSTRAINT "FK_161009326bd37f66e42195ef61d"`);
        await queryRunner.query(`ALTER TABLE "kb_folder" DROP CONSTRAINT "FK_d75bd458c36ccad6a3d784cfb81"`);
        await queryRunner.query(`ALTER TABLE "knowledge_base" DROP CONSTRAINT "FK_f39683bc3c87e158ee5afffdbac"`);
        await queryRunner.query(`ALTER TABLE "knowledge_base" DROP CONSTRAINT "FK_a47b1575e8f2c2cc377a9cc40f0"`);
        await queryRunner.query(`ALTER TABLE "workspace_member" DROP CONSTRAINT "FK_82b74268d8b7e1574fd744b3903"`);
        await queryRunner.query(`ALTER TABLE "workspace_member" DROP CONSTRAINT "FK_73d466cb93234025fe379fa5873"`);
        await queryRunner.query(`ALTER TABLE "workspace" DROP CONSTRAINT "FK_988cf8ee530a5f8a2d56269955b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6fd20035420a32ac56139d17f6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8c9b43712e39780ad1d53380b7"`);
        await queryRunner.query(`ALTER TABLE "flow_version" ALTER COLUMN "created_by" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "flow_version" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "flow_version" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "flow_version" ALTER COLUMN "bot_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "flow_version" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "flow_version" DROP COLUMN "versionNumber"`);
        await queryRunner.query(`ALTER TABLE "flow_version" DROP COLUMN "data"`);
        await queryRunner.query(`ALTER TABLE "flow_version" DROP COLUMN "flowId"`);
        await queryRunner.query(`ALTER TABLE "flow_version" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "flow_version" ADD "versionNumber" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "flow_version" ADD "data" jsonb NOT NULL`);
        await queryRunner.query(`ALTER TABLE "flow_version" ADD "flowId" uuid NOT NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e3a3ba47b7ca00fd23be4ebd6c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3d0a7155eafd75ddba5a701336"`);
        await queryRunner.query(`DROP TABLE "role_permission"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7b6ddcbc20f35c452fbde742e8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1306d6c971218f52de9eb25871"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f7f36a37f00bf828c64235a64f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_540a1d7e19f73eed9317c514b7"`);
        await queryRunner.query(`DROP TABLE "data_access_log"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2ad7930a7c2af80585c8c1b770"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4a7f36346480a56b810efea4a2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_951e6339a77994dfbad976b35c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d65f841d6520dc60a9dfcb9367"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cb11bd5b662431ea0ac455a27d"`);
        await queryRunner.query(`DROP TABLE "audit_log"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0cc3da9bd6517136ef4a68fec3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_844910ae4694cdde8c1c428cc9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_46f3d06fc514b5dbd701949d22"`);
        await queryRunner.query(`DROP TABLE "widget_deployment"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_869c687d5115dda182f23c3d7d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eec8048c9de6987375d69bce8f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_73d825a2b5257fecae3fa44391"`);
        await queryRunner.query(`DROP TABLE "widget_version"`);
        await queryRunner.query(`DROP TABLE "message_feedback"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7fe3e887d78498d9c9813375ce"`);
        await queryRunner.query(`DROP TABLE "message"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b6a81d0030252361a6a7326dd5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4414991bced54350c7ad1378fc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0d448862b6090e5239102fb2db"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_91fdb6236859404ddf7c5f6437"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aaebf689e2996177947248df93"`);
        await queryRunner.query(`DROP TABLE "conversation"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_82da258fe45382a03c820a8daf"`);
        await queryRunner.query(`DROP TABLE "channel"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_159a73113affedc7d5638ce6c2"`);
        await queryRunner.query(`DROP TABLE "bot_knowledge_base"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e45750f69e8b0280974c298b82"`);
        await queryRunner.query(`DROP TABLE "bot"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8718c0c649f54b2e26e819018e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1bdb0ba34522870a1d86dc4514"`);
        await queryRunner.query(`DROP TABLE "ai_conversation"`);
        await queryRunner.query(`DROP TABLE "file"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_82bbbc66b3d756c9b6195e54a2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b12e2bba2745c94014eed8a020"`);
        await queryRunner.query(`DROP TABLE "flow_execution"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_38fca24c8eadabf06167f4d6c9"`);
        await queryRunner.query(`DROP TABLE "node_execution"`);
        await queryRunner.query(`DROP TABLE "flow_version"`);
        await queryRunner.query(`DROP TABLE "flow"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a5a2e06b4f4afbdaee17a9df17"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5ac913b616a1320e4e443f9ee6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_49ac0d03296afd3cad2a4be75b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_81d0c0117227d233206d06fa95"`);
        await queryRunner.query(`DROP TABLE "channel_connection"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_45dbb885e2a77019931fc5ed8f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7759e3294e12c1bd976f2ca8ac"`);
        await queryRunner.query(`DROP TABLE "channel_credential"`);
        await queryRunner.query(`DROP TABLE "node_type"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8bdc07e9c41ce8d83730f0f5d8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aedc307c7e60ecb138e3f90ff8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9f7d684c30d9d0cdbc24322de8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_928b7aa1754e08e1ed7052cb9d"`);
        await queryRunner.query(`DROP TABLE "notification"`);
        await queryRunner.query(`DROP TABLE "role"`);
        await queryRunner.query(`DROP TABLE "permission"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3d2f174ef04fb312fdebd0ddc5"`);
        await queryRunner.query(`DROP TABLE "session"`);
        await queryRunner.query(`DROP TABLE "status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5d9508325a862b5b3c7c819de3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a85d07a63679df4dd094bfc756"`);
        await queryRunner.query(`DROP TABLE "invoice"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_192fa04382405c62d6e7a0eedf"`);
        await queryRunner.query(`DROP TABLE "usage_quota"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4919f4488c35799176dfd3c143"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c60cbdbd21c49a01596ec24d1f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5fde988e5d9b9a522d70ebec27"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6026acc5aa817269a5f7463526"`);
        await queryRunner.query(`DROP TABLE "subscription"`);
        await queryRunner.query(`DROP TABLE "plan"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c9c20a97f6b381386a315f74c3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_63a1ffd56c6903021d2c5b6aaa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0253cc148d22e4ba68ca3ededf"`);
        await queryRunner.query(`DROP TABLE "webhook_event"`);
        await queryRunner.query(`DROP TABLE "system_ai_settings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_18f3bc73d7d2692f732cc974f0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d7b00762ea27339b5f6ea53bfa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d4b3d0a0eac463e2224513fff7"`);
        await queryRunner.query(`DROP TABLE "ai_usage_log"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2a55b8ba19368d0e6499ba5df1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3522a3e473b56a703fe8d98c95"`);
        await queryRunner.query(`DROP TABLE "workspace_ai_provider_configs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ec0f1703bed5fb29ea5e0afe16"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bca82934cd53e143c74a2ff97c"`);
        await queryRunner.query(`DROP TABLE "user_ai_provider_configs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b4e4ef106d84e38e8577cd965d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2bdd8f45e064bac6f99cbbe91d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7299ed156a084d7e97df80b7ff"`);
        await queryRunner.query(`DROP TABLE "ai_provider_configs"`);
        await queryRunner.query(`DROP TABLE "ai_providers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2b11e5e325ab1cf316a7b1d2b2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4f4af60aee1133f7e8a8043cfb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e9e43161d0e1e48cc608513802"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f37a6fd48b5ba27e7da2d4a8e6"`);
        await queryRunner.query(`DROP TABLE "kb_chunk"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ba6efe5217f9ccca718f480f96"`);
        await queryRunner.query(`DROP TABLE "rag_feedback"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe4cabddacd8bea491dda43610"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c348ba14b55e6e3452b050a612"`);
        await queryRunner.query(`DROP TABLE "kb_document_version"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b29ab77551196c32dbf229c477"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e0a623b6a641e6cb084ffd1ae8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6ee0459e7db0b730836e102d9b"`);
        await queryRunner.query(`DROP TABLE "kb_document"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_161009326bd37f66e42195ef61"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d75bd458c36ccad6a3d784cfb8"`);
        await queryRunner.query(`DROP TABLE "kb_folder"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8ae166c823e535eb731f333522"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f39683bc3c87e158ee5afffdba"`);
        await queryRunner.query(`DROP TABLE "knowledge_base"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0eab76d5a9c509930a9f3d7a10"`);
        await queryRunner.query(`DROP TABLE "workspace_member"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0d706c438a9b1ae0ac9806a201"`);
        await queryRunner.query(`DROP TABLE "workspace"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0cd76a8cdee62eeff31d384b73"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6937e802be2946855a3ad0e6be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7a4fd2a547828e5efe420e50d1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5e3a2b86fd9a9c22c266ae0473"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e12875dfb3b1d92d7d7c5377e2"`);
        await queryRunner.query(`DROP TABLE "user"`);
    }

}
