import { MigrationInterface, QueryRunner } from "typeorm";

export class Initial21765936529335 implements MigrationInterface {
    name = 'Initial21765936529335'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "knowledge_base" DROP CONSTRAINT "FK_f39683bc3c87e158ee5afffdbac"`);
        await queryRunner.query(`ALTER TABLE "knowledge_base" DROP CONSTRAINT "FK_a47b1575e8f2c2cc377a9cc40f0"`);
        await queryRunner.query(`ALTER TABLE "kb_folder" DROP CONSTRAINT "FK_161009326bd37f66e42195ef61d"`);
        await queryRunner.query(`ALTER TABLE "kb_document" DROP CONSTRAINT "FK_e98a2d3732711bfa802d8de314e"`);
        await queryRunner.query(`ALTER TABLE "kb_document" DROP CONSTRAINT "FK_e0a623b6a641e6cb084ffd1ae8c"`);
        await queryRunner.query(`ALTER TABLE "kb_document_version" DROP CONSTRAINT "FK_e828d02073fa95cca8fda16ad60"`);
        await queryRunner.query(`ALTER TABLE "rag_feedback" DROP CONSTRAINT "FK_8b0eac5cbe2159dc9070a1e52be"`);
        await queryRunner.query(`ALTER TABLE "kb_chunk" DROP CONSTRAINT "FK_9f2ef0102da59042a85e6f21fb0"`);
        await queryRunner.query(`ALTER TABLE "flow_version" DROP CONSTRAINT "FK_8c9b43712e39780ad1d53380b74"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ae8c2c4e8b7e8b2b8c9e8b2b8c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b29ab77551196c32dbf229c477"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe4cabddacd8bea491dda43610"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ba6efe5217f9ccca718f480f96"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4f4af60aee1133f7e8a8043cfb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2b11e5e325ab1cf316a7b1d2b2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8c9b43712e39780ad1d53380b7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6fd20035420a32ac56139d17f6"`);
        await queryRunner.query(`ALTER TABLE "knowledge_base" DROP COLUMN "similarity_threshold"`);
        await queryRunner.query(`ALTER TABLE "knowledge_base" DROP COLUMN "top_k"`);
        await queryRunner.query(`ALTER TABLE "knowledge_base" DROP COLUMN "live_version_id"`);
        await queryRunner.query(`ALTER TABLE "knowledge_base" DROP COLUMN "is_public"`);
        await queryRunner.query(`ALTER TABLE "knowledge_base" DROP COLUMN "icon"`);
        await queryRunner.query(`ALTER TABLE "knowledge_base" DROP COLUMN "color"`);
        await queryRunner.query(`ALTER TABLE "knowledge_base" DROP COLUMN "tags"`);
        await queryRunner.query(`ALTER TABLE "kb_folder" DROP COLUMN "path"`);
        await queryRunner.query(`ALTER TABLE "kb_document" DROP COLUMN "current_version_id"`);
        await queryRunner.query(`ALTER TABLE "kb_document" DROP COLUMN "slug"`);
        await queryRunner.query(`ALTER TABLE "kb_document" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "kb_document" DROP COLUMN "tags"`);
        await queryRunner.query(`ALTER TABLE "kb_document_version" DROP COLUMN "token_count"`);
        await queryRunner.query(`ALTER TABLE "kb_document_version" DROP COLUMN "chunk_count"`);
        await queryRunner.query(`ALTER TABLE "kb_document_version" DROP COLUMN "is_live"`);
        await queryRunner.query(`ALTER TABLE "kb_document_version" DROP COLUMN "processing_started_at"`);
        await queryRunner.query(`ALTER TABLE "kb_document_version" DROP COLUMN "processing_completed_at"`);
        await queryRunner.query(`ALTER TABLE "kb_document_version" DROP COLUMN "version_label"`);
        await queryRunner.query(`ALTER TABLE "kb_document_version" DROP COLUMN "content_text"`);
        await queryRunner.query(`ALTER TABLE "kb_document_version" DROP COLUMN "content_html"`);
        await queryRunner.query(`ALTER TABLE "kb_document_version" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "kb_document_version" DROP COLUMN "qdrant_collection"`);
        await queryRunner.query(`ALTER TABLE "kb_document_version" DROP COLUMN "embedding_model"`);
        await queryRunner.query(`ALTER TABLE "kb_document_version" DROP COLUMN "error_message"`);
        await queryRunner.query(`ALTER TABLE "rag_feedback" DROP COLUMN "message_id"`);
        await queryRunner.query(`ALTER TABLE "rag_feedback" DROP COLUMN "created_by"`);
        await queryRunner.query(`ALTER TABLE "rag_feedback" DROP COLUMN "comment"`);
        await queryRunner.query(`ALTER TABLE "kb_chunk" DROP COLUMN "documentId"`);
        await queryRunner.query(`ALTER TABLE "flow_version" DROP COLUMN "flowId"`);
        await queryRunner.query(`ALTER TABLE "flow_version" DROP COLUMN "data"`);
        await queryRunner.query(`ALTER TABLE "flow_version" DROP COLUMN "versionNumber"`);
        await queryRunner.query(`ALTER TABLE "flow_version" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "knowledge_base" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "kb_document_version" ADD "content" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "kb_document_version" ADD "metadata" jsonb`);
        await queryRunner.query(`ALTER TABLE "kb_document_version" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "kb_document_version" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "rag_feedback" ADD "knowledge_base_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rag_feedback" ADD "document_id" uuid`);
        await queryRunner.query(`ALTER TABLE "rag_feedback" ADD "user_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rag_feedback" ADD "bot_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rag_feedback" ADD "question" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rag_feedback" ADD "answer" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rag_feedback" ADD "sources" jsonb NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rag_feedback" ADD "feedback" character varying`);
        await queryRunner.query(`ALTER TABLE "rag_feedback" ADD "is_helpful" boolean`);
        await queryRunner.query(`ALTER TABLE "rag_feedback" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "rag_feedback" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "kb_chunk" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "kb_chunk" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "flow_version" ADD "flowId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "flow_version" ADD "data" jsonb NOT NULL`);
        await queryRunner.query(`ALTER TABLE "flow_version" ADD "versionNumber" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "flow_version" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "knowledge_base" ALTER COLUMN "embedding_model" SET DEFAULT 'text-embedding-3-small'`);
        await queryRunner.query(`ALTER TABLE "kb_document" ALTER COLUMN "name" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "kb_document" ALTER COLUMN "title" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "kb_document" ALTER COLUMN "content" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "kb_document" ALTER COLUMN "processing_status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "kb_document" ALTER COLUMN "processing_status" SET DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "kb_document" DROP COLUMN "processing_error"`);
        await queryRunner.query(`ALTER TABLE "kb_document" ADD "processing_error" character varying`);
        await queryRunner.query(`ALTER TABLE "kb_document" DROP COLUMN "file_size"`);
        await queryRunner.query(`ALTER TABLE "kb_document" ADD "file_size" character varying`);
        await queryRunner.query(`ALTER TABLE "kb_document" ALTER COLUMN "type" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "kb_document" ALTER COLUMN "type" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "rag_feedback" ALTER COLUMN "rating" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "kb_chunk" ALTER COLUMN "start_char" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "kb_chunk" ALTER COLUMN "end_char" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "kb_chunk" ALTER COLUMN "token_count" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "kb_chunk" ALTER COLUMN "token_count" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "kb_chunk" DROP COLUMN "embedding_error"`);
        await queryRunner.query(`ALTER TABLE "kb_chunk" ADD "embedding_error" character varying`);
        await queryRunner.query(`ALTER TABLE "flow_version" ALTER COLUMN "bot_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "flow_version" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "flow_version" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "flow_version" ALTER COLUMN "created_by" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "flow_version" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "flow_version" ADD "description" character varying`);
        await queryRunner.query(`CREATE INDEX "IDX_a47b1575e8f2c2cc377a9cc40f" ON "knowledge_base" ("created_by") `);
        await queryRunner.query(`CREATE INDEX "IDX_eca4b4cdf538be462b42c7c65c" ON "rag_feedback" ("knowledge_base_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c28603c727679940ff131eda9f" ON "rag_feedback" ("document_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d12ed4537e1103cd11cfe1b51c" ON "rag_feedback" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d8d931d5410e54404e3ee0f29c" ON "rag_feedback" ("bot_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8c9b43712e39780ad1d53380b7" ON "flow_version" ("bot_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6fd20035420a32ac56139d17f6" ON "flow_version" ("bot_id", "version") `);
        await queryRunner.query(`ALTER TABLE "kb_folder" ADD CONSTRAINT "FK_161009326bd37f66e42195ef61d" FOREIGN KEY ("parent_id") REFERENCES "kb_folder"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kb_document" ADD CONSTRAINT "FK_e0a623b6a641e6cb084ffd1ae8c" FOREIGN KEY ("folder_id") REFERENCES "kb_folder"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "flow_version" ADD CONSTRAINT "FK_8c9b43712e39780ad1d53380b74" FOREIGN KEY ("bot_id") REFERENCES "bot"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "flow_version" DROP CONSTRAINT "FK_8c9b43712e39780ad1d53380b74"`);
        await queryRunner.query(`ALTER TABLE "kb_document" DROP CONSTRAINT "FK_e0a623b6a641e6cb084ffd1ae8c"`);
        await queryRunner.query(`ALTER TABLE "kb_folder" DROP CONSTRAINT "FK_161009326bd37f66e42195ef61d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6fd20035420a32ac56139d17f6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8c9b43712e39780ad1d53380b7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d8d931d5410e54404e3ee0f29c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d12ed4537e1103cd11cfe1b51c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c28603c727679940ff131eda9f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eca4b4cdf538be462b42c7c65c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a47b1575e8f2c2cc377a9cc40f"`);
        await queryRunner.query(`ALTER TABLE "flow_version" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "flow_version" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "flow_version" ALTER COLUMN "created_by" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "flow_version" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "flow_version" ADD "description" character varying`);
        await queryRunner.query(`ALTER TABLE "flow_version" ALTER COLUMN "bot_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "kb_chunk" DROP COLUMN "embedding_error"`);
        await queryRunner.query(`ALTER TABLE "kb_chunk" ADD "embedding_error" text`);
        await queryRunner.query(`ALTER TABLE "kb_chunk" ALTER COLUMN "token_count" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "kb_chunk" ALTER COLUMN "token_count" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "kb_chunk" ALTER COLUMN "end_char" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "kb_chunk" ALTER COLUMN "start_char" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "rag_feedback" ALTER COLUMN "rating" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "kb_document" ALTER COLUMN "type" SET DEFAULT 'file'`);
        await queryRunner.query(`ALTER TABLE "kb_document" ALTER COLUMN "type" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "kb_document" DROP COLUMN "file_size"`);
        await queryRunner.query(`ALTER TABLE "kb_document" ADD "file_size" bigint`);
        await queryRunner.query(`ALTER TABLE "kb_document" DROP COLUMN "processing_error"`);
        await queryRunner.query(`ALTER TABLE "kb_document" ADD "processing_error" text`);
        await queryRunner.query(`ALTER TABLE "kb_document" ALTER COLUMN "processing_status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "kb_document" ALTER COLUMN "processing_status" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "kb_document" ALTER COLUMN "content" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "kb_document" ALTER COLUMN "title" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "kb_document" ALTER COLUMN "name" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "knowledge_base" ALTER COLUMN "embedding_model" SET DEFAULT 'text-embedding-004'`);
        await queryRunner.query(`ALTER TABLE "flow_version" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "flow_version" DROP COLUMN "versionNumber"`);
        await queryRunner.query(`ALTER TABLE "flow_version" DROP COLUMN "data"`);
        await queryRunner.query(`ALTER TABLE "flow_version" DROP COLUMN "flowId"`);
        await queryRunner.query(`ALTER TABLE "kb_chunk" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "kb_chunk" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "rag_feedback" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "rag_feedback" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "rag_feedback" DROP COLUMN "is_helpful"`);
        await queryRunner.query(`ALTER TABLE "rag_feedback" DROP COLUMN "feedback"`);
        await queryRunner.query(`ALTER TABLE "rag_feedback" DROP COLUMN "sources"`);
        await queryRunner.query(`ALTER TABLE "rag_feedback" DROP COLUMN "answer"`);
        await queryRunner.query(`ALTER TABLE "rag_feedback" DROP COLUMN "question"`);
        await queryRunner.query(`ALTER TABLE "rag_feedback" DROP COLUMN "bot_id"`);
        await queryRunner.query(`ALTER TABLE "rag_feedback" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "rag_feedback" DROP COLUMN "document_id"`);
        await queryRunner.query(`ALTER TABLE "rag_feedback" DROP COLUMN "knowledge_base_id"`);
        await queryRunner.query(`ALTER TABLE "kb_document_version" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "kb_document_version" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "kb_document_version" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "kb_document_version" DROP COLUMN "content"`);
        await queryRunner.query(`ALTER TABLE "knowledge_base" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "flow_version" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "flow_version" ADD "versionNumber" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "flow_version" ADD "data" jsonb NOT NULL`);
        await queryRunner.query(`ALTER TABLE "flow_version" ADD "flowId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "kb_chunk" ADD "documentId" uuid`);
        await queryRunner.query(`ALTER TABLE "rag_feedback" ADD "comment" text`);
        await queryRunner.query(`ALTER TABLE "rag_feedback" ADD "created_by" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rag_feedback" ADD "message_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "kb_document_version" ADD "error_message" text`);
        await queryRunner.query(`ALTER TABLE "kb_document_version" ADD "embedding_model" character varying`);
        await queryRunner.query(`ALTER TABLE "kb_document_version" ADD "qdrant_collection" character varying`);
        await queryRunner.query(`ALTER TABLE "kb_document_version" ADD "status" character varying NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "kb_document_version" ADD "content_html" text`);
        await queryRunner.query(`ALTER TABLE "kb_document_version" ADD "content_text" text`);
        await queryRunner.query(`ALTER TABLE "kb_document_version" ADD "version_label" character varying`);
        await queryRunner.query(`ALTER TABLE "kb_document_version" ADD "processing_completed_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "kb_document_version" ADD "processing_started_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "kb_document_version" ADD "is_live" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "kb_document_version" ADD "chunk_count" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "kb_document_version" ADD "token_count" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "kb_document" ADD "tags" text`);
        await queryRunner.query(`ALTER TABLE "kb_document" ADD "status" character varying NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "kb_document" ADD "slug" character varying`);
        await queryRunner.query(`ALTER TABLE "kb_document" ADD "current_version_id" uuid`);
        await queryRunner.query(`ALTER TABLE "kb_folder" ADD "path" character varying`);
        await queryRunner.query(`ALTER TABLE "knowledge_base" ADD "tags" text`);
        await queryRunner.query(`ALTER TABLE "knowledge_base" ADD "color" character varying NOT NULL DEFAULT '#3B82F6'`);
        await queryRunner.query(`ALTER TABLE "knowledge_base" ADD "icon" character varying`);
        await queryRunner.query(`ALTER TABLE "knowledge_base" ADD "is_public" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "knowledge_base" ADD "live_version_id" uuid`);
        await queryRunner.query(`ALTER TABLE "knowledge_base" ADD "top_k" integer NOT NULL DEFAULT '5'`);
        await queryRunner.query(`ALTER TABLE "knowledge_base" ADD "similarity_threshold" double precision NOT NULL DEFAULT '0.7'`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6fd20035420a32ac56139d17f6" ON "flow_version" ("bot_id", "version") `);
        await queryRunner.query(`CREATE INDEX "IDX_8c9b43712e39780ad1d53380b7" ON "flow_version" ("bot_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2b11e5e325ab1cf316a7b1d2b2" ON "kb_chunk" ("embedding_status") `);
        await queryRunner.query(`CREATE INDEX "IDX_4f4af60aee1133f7e8a8043cfb" ON "kb_chunk" ("vector_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ba6efe5217f9ccca718f480f96" ON "rag_feedback" ("message_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_fe4cabddacd8bea491dda43610" ON "kb_document_version" ("document_id", "version") `);
        await queryRunner.query(`CREATE INDEX "IDX_b29ab77551196c32dbf229c477" ON "kb_document" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_ae8c2c4e8b7e8b2b8c9e8b2b8c" ON "kb_folder" ("created_by") `);
        await queryRunner.query(`ALTER TABLE "flow_version" ADD CONSTRAINT "FK_8c9b43712e39780ad1d53380b74" FOREIGN KEY ("bot_id") REFERENCES "bot"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kb_chunk" ADD CONSTRAINT "FK_9f2ef0102da59042a85e6f21fb0" FOREIGN KEY ("documentId") REFERENCES "kb_document"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rag_feedback" ADD CONSTRAINT "FK_8b0eac5cbe2159dc9070a1e52be" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kb_document_version" ADD CONSTRAINT "FK_e828d02073fa95cca8fda16ad60" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kb_document" ADD CONSTRAINT "FK_e0a623b6a641e6cb084ffd1ae8c" FOREIGN KEY ("folder_id") REFERENCES "kb_folder"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kb_document" ADD CONSTRAINT "FK_e98a2d3732711bfa802d8de314e" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kb_folder" ADD CONSTRAINT "FK_161009326bd37f66e42195ef61d" FOREIGN KEY ("parent_id") REFERENCES "kb_folder"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "knowledge_base" ADD CONSTRAINT "FK_a47b1575e8f2c2cc377a9cc40f0" FOREIGN KEY ("created_by") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "knowledge_base" ADD CONSTRAINT "FK_f39683bc3c87e158ee5afffdbac" FOREIGN KEY ("workspace_id") REFERENCES "workspace"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
