-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Flows Table
create table public.flows (
  id bigint generated by default as identity primary key,
  user_id text,
  name text not null,
  description text,
  status text default 'draft',
  version integer default 1,
  data jsonb default '{}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Workflow Executions Table
create table public.workflow_executions (
  id bigint generated by default as identity primary key,
  flow_version_id bigint, -- In real app, link to flow_versions table
  conversation_id bigint,
  status text not null, -- 'running', 'completed', 'failed', 'cancelled'
  started_at timestamp with time zone default timezone('utc'::text, now()) not null,
  completed_at timestamp with time zone,
  input_data jsonb default '{}'::jsonb,
  output_data jsonb,
  error_message text,
  total_nodes integer default 0,
  completed_nodes integer default 0
);

-- Node Executions Table
create table public.node_executions (
  id bigint generated by default as identity primary key,
  workflow_execution_id bigint references public.workflow_executions(id) on delete cascade,
  node_id text not null,
  node_type text not null,
  node_label text,
  status text not null, -- 'pending', 'running', 'completed', 'failed', 'skipped'
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  execution_time_ms integer,
  input_data jsonb default '{}'::jsonb,
  output_data jsonb,
  error_message text
);

-- RLS Policies (Optional - Enable if using Supabase Auth directly)
alter table public.flows enable row level security;
alter table public.workflow_executions enable row level security;
alter table public.node_executions enable row level security;

-- Simple policy: Allow all access for now (since we handle auth in backend via Casdoor)
create policy "Allow all access" on public.flows for all using (true);
create policy "Allow all access" on public.workflow_executions for all using (true);
create policy "Allow all access" on public.node_executions for all using (true);
